description: Turn off water heater in the most expensive hours
mode: single
trigger:
  - platform: state
    entity_id: sensor.nordpool_kwh_oslo_nok_3_10_025
condition: []
action:
  - choose:
      - conditions:
          - condition: template
            value_template: >-
              {{
              ([(state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','today')[0]
              |
                              float(default=0)),
                              (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','today')[1] |
                              float(default=0)),
                              (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','today')[2] |
                              float(default=0)),
                              (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','today')[3] |
                              float(default=0)),
                              (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','today')[4] |
                              float(default=0)),
                              (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','today')[5] |
                              float(default=0)),
                              (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','today')[6] |
                              float(default=0)),
                              (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','today')[7] |
                              float(default=0))] | sort)[4] >=
                              state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','current_price') | float }}
          - condition: time
            after: "00:00"
            before: "08:00"
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
        sequence:
          - service: switch.turn_on
            target:
              entity_id: switch.varmtvannsbereder
            data: {}
      - conditions:
          - condition: template
            value_template: |2-
                {{ ([
                                (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','today')[14] |
                                float(default=0)),
                                (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','today')[15] |
                                float(default=0)),
                                (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','today')[16] |
                                float(default=0)),
                                (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','today')[17] |
                                float(default=0)),
                                (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','today')[18] |
                                float(default=0)),
                                (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','today')[19] |
                                float(default=0))] | sort)[1] >=
                                state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','current_price') | float }}
          - condition: time
            after: "15:00"
            before: "20:00"
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
        sequence:
          - service: switch.turn_on
            target:
              entity_id: switch.varmtvannsbereder
            data: {}
      - conditions:
          - condition: template
            value_template: |2-
               {{ ([
                                (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','today')[0] |
                                float(default=0)),
                                (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','today')[1] |
                                float(default=0)),
                                (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','today')[2] |
                                float(default=0)),
                                (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','today')[3] |
                                float(default=0)),
                                (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','today')[4] |
                                float(default=0)),
                                (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','today')[5] |
                                float(default=0)),
                                (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','today')[6] |
                                float(default=0)),
                                (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','today')[7] |
                                float(default=0)),
                                (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','today')[8] |
                                float(default=0)),
                                (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','today')[9] |
                                float(default=0)),
                                (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','today')[10] |
                                float(default=0)),
                                (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','today')[11] |
                                float(default=0)),
                                (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','today')[12] |
                                float(default=0)),
                                (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','today')[13] |
                                float(default=0)),
                                (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','today')[14] |
                                float(default=0)),
                                (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','today')[15] |
                                float(default=0)),
                                (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','today')[16] |
                                float(default=0)),
                                (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','today')[17] |
                                float(default=0)),
                                (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','today')[18] |
                                float(default=0)),
                                (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','today')[19] |
                                float(default=0)),
                                (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','today')[20] |
                                float(default=0)),
                                (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','today')[21] |
                                float(default=0)),
                                (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','today')[22] |
                                float(default=0)),
                                (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','today')[23] |
                                float(default=0))] | sort)[20] >=
                                state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','current_price') | float }}
          - condition: time
            after: "00:01"
            before: "23:59"
            weekday:
              - sat
              - sun
        sequence:
          - service: switch.turn_on
            target:
              entity_id: switch.varmtvannsbereder
            data: {}
    default:
      - service: switch.turn_off
        target:
          entity_id: switch.varmtvannsbereder
        data: {}
alias: Water Heater
