-   id: '1582583923026'
    alias: Water Heater
    description: Turn off water heater during most expensive hours
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.nordpool_kwh_oslo_nok_3_10_025
        domain: switch
        for:
          hours: 0
          minutes: 0
          seconds: 0
      - platform: time_pattern
        seconds: '5'
    condition: []
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: >-
                  {{ (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025', 'today')[0:7] | sort(false))[4] | float(default=0) >=
                      state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','current_price') | float }}
              - condition: time
                after: "00:00"
                before: "08:00"
                weekday:
                  - mon
                  - tue
                  - wed
                  - thu
                  - fri
            sequence:
              - service: switch.turn_on
                target:
                  entity_id: switch.varmtvannsbereder
                data: {}
          - conditions:
              - condition: template
                value_template: |2-
                  {{ (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025', 'today')[14:17] | sort(false))[1] | float(default=0) >=
                                    state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','current_price') | float }}
              - condition: time
                after: "15:00"
                before: "20:00"
                weekday:
                  - mon
                  - tue
                  - wed
                  - thu
                  - fri
            sequence:
              - service: switch.turn_on
                target:
                  entity_id: switch.varmtvannsbereder
                data: {}
          - conditions:
              - condition: template
                value_template: |2-
                  {{ (state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025', 'today')[0:23] | sort(false))[20] | float(default=0) >=
                                    state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','current_price') | float }}
              - condition: time
                after: "00:01"
                before: "23:59"
                weekday:
                  - sat
                  - sun
            sequence:
              - service: switch.turn_on
                target:
                  entity_id: switch.varmtvannsbereder
                data: {}
        default:
          - service: switch.turn_off
            target:
              entity_id: switch.varmtvannsbereder
            data: {}

- id: Frost notifications
  alias: Frost Warning
  description: Send notification when temp is below 2C.
  trigger:
  - platform: numeric_state
    entity_id: sensor.weather_temperature
    below: 2
    attribute: temperature
  condition: []
  action:
  - device_id: 22c6b76a1091a83cbd2affac41a448ff
    domain: mobile_app
    type: notify
    message: Frostvarsel. Temperaturen er under 2C.
    title: Frostvarsel
  - condition: time
    after: 05:00:00
    before: 09:00:00
    weekday:
    - fri
    - thu
    - wed
    - tue
    - mon
  mode: single
- id: Temp warning water heater
  alias: Water Heater Warning
  description: Send notification when the water heater plug is too warm.
  trigger:
  - platform: numeric_state
    entity_id: sensor.varmtvannsbereder_temperature
    above: 60
    attribute: temperature
  condition: []
  action:
  - device_id: 22c6b76a1091a83cbd2affac41a448ff
    domain: mobile_app
    type: notify
    message: Varmevarsel - Bereder. Temperaturen er over 60C!
    title: Varmevarsel
  mode: single