
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
input_number: !include input_number.yaml

frontend:
  themes: !include_dir_merge_named themes

input_boolean: !include input_boolean.yaml
binary_sensor: !include binary_sensor.yaml
sensor: !include sensor.yaml

# Date and clock
template:
  - sensor:
    - name: "Date and time"
      state: "{{ as_timestamp(states('sensor.date_time_iso')) | timestamp_custom('%A %B %-d, %H:%M') }}"
      icon: "mdi:calendar-clock"

  - sensor:
    - name: "Current time"
      state: "{{ as_timestamp(states('sensor.date_time_iso')) | timestamp_custom('%H:%M') }}"
      icon: "mdi:clock"
      
ios:
    actions:
    - name: Garage
      background_color: "#000000"
      label:
        text: "Garage Door"
        color: "#ff0000"
      icon:
        icon: earth
        color: "#ffffff"